services:
  - type: web
    name: downloader-backend
    env: node
    plan: free
    buildCommand: "npm install && apt-get update && apt-get install -y ffmpeg"
    startCommand: "node server.js"
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 18